name: Epic 🏔
description: Coordinate an effort of tasks not bound by time to complete.
labels: "type: epic 🏔"
body:
  - type: markdown
    attributes:
      value:
        Use this template for to track higher-level efforts that typically can't
        get completed within a two week sprint.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description:
        "What problem (or opportunity) are we solving? Why are we solving it? Is
        there supporting user conversations or research? How does this affect
        different parts of IBM and beyond?"
    validations:
      required: true
  - type: textarea
    id: stories
    attributes:
      label: Job stories
      description: "Describe job stories to make the value we deliver to our makers clear, and what it will enable them to do."
      placeholder: "When ___, I want to ___, so I can ___."
  - type: textarea
    id: success
    attributes:
      label: Success measures
      description: "How we will determine whether the problem as been solved, should that be qualitative and/or quantitative measures?"
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: "Describe the tasks required to complete the epic."
      placeholder: "- [ ] Task"
