name: Feature request 💡
description: Suggest an idea for this project.
labels: "type: enhancement 💡"
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value:
        Use this template if you want to request a new feature, or a change to
        an existing feature. If you are reporting a bug or problem, please use
        the bug template instead.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description:
        "Please describe your request in one or two sentences. Clarify if you
        are asking for design, development, or both design and development."
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: "Provide the business reasons for this request."
  - type: textarea
    id: metrics
    attributes:
      label: Success metrics
      description:
        "Describe the full user experience for this feature. Also define the
        metrics by which we can measure success/failure for the user."
  - type: textarea
    id: functionality
    attributes:
      label: Required functionality
      description:
        "Highlight any must have needs and functionality for the request. This
        should not be a full list of functionality; the Carbon team will work
        with you to define functionality based on the desired experience."
  - type: textarea
    id: timeline
    attributes:
      label: Specific timeline issues / requests
      description:
        "Do you want this work within a specific time period? Is it related to
        an upcoming release?"
  - type: input
    id: resources
    attributes:
      label: Available resources
      description: "What resources do you have to assist this effort?"
  - type: markdown
    attributes:
      value: "_Carbon is a collaborative system. We encourage teams to build
        with us and submit contributions._"
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: Please confirm the following.
      options:
        - label: I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon-platform/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
