#!/bin/sh
#
# Copyright IBM Corp. 2021, 2021
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#

mkdir -p services/web-app/certificates

mkcert \
  -cert-file=./services/web-app/certificates/localhost.crt \
  -key-file=./services/web-app/certificates/localhost.key \
  localhost "*.localhost"
