#!/bin/sh
#
# Copyright IBM Corp. 2021, 2022
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#
set -e

echo "Removing tsbuildinfo files"
find . -name "*.tsbuildinfo" | xargs rm -f

echo "Removing .test-coverage folders"
find . -name ".test-coverage" | xargs rm -rf
