#!/bin/sh
#
# Copyright IBM Corp. 2021, 2022
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#

set -e

prettier --check --write .

stylelint --fix '**/*.{css,scss}'

eslint --fix --max-warnings=0 --ext .js,.cjs,.mjs,.jsx,.ts,.tsx .

# Lint once more to ensure no thrashing occurred
scripts/lint
