#!/bin/sh
#
# Copyright IBM Corp. 2021, 2022
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#

set -e

prettier --check .

stylelint '**/*.{css,scss}'

eslint --max-warnings=0 --ext .js,.cjs,.mjs,.jsx,.ts,.tsx .
