#!/bin/sh
#
# Copyright IBM Corp. 2021, 2021
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#

# Fail immediately on errors
set -e

scripts/micromanage version > micromanage-updated.json

scripts/micromanage docker-push < micromanage-updated.json

# Cleanup
rm micromanage-updated.json
