#!/bin/sh
#
# Copyright IBM Corp. 2021, 2022
#
# This source code is licensed under the Apache-2.0 license found in the
# LICENSE file in the root directory of this source tree.
#

set -e

if [ "$CI" = "true" ]; then
  echo '🤖 Running in a CI environment. Skipping prepare steps.'
  exit 0
fi

npx husky install

echo '🏗️ Building packages and APIs...'
npm run packages:build
echo '✅ Done!\n'

echo '🏗️ Generating data-graph schema...'
npm -w services/data-graph run build:schema
echo '✅ Done!\n'
