name: Publish Schemas
on:
  push:
    tags:
      - '@carbon-platform/schemas@*.*.*'

  # Enable running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup Node 🏗
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Bootstrap Micromanage 🥾
        run: npm run micromanage:bootstrap

      - name: Publish 🚀
        run: node packages/micromanage publish @carbon-platform/schemas
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
